baseURL = "https://gurucodes-67a76.web.app/"
languageCode = "en-us"
title = "GuruCodes.io"
ignoreErrors = ["error-remote-getjson"]
publishDir = "../public"
pygmentsStyle = "atom"
pygmentsUseClasses = true
enableRobotsTXT = true

[outputs]
home = ["HTML", "RSS", "Algolia"]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params]
mainSections = ["lessons", "snippets"]

[params.algolia]
vars = ["title", "description", "summary", "date", "publishdate", "lastmod", "permalink"]
params = ["tags"]

[markup.goldmark.renderer]
unsafe= true

